# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saved_credentials.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import traceback

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QStringListModel
from PyQt5.QtGui import QStandardItem, QIcon
from PyQt5.QtWidgets import QAction

from scr.classes.Credential.CredentialHadler import CredentialHadler
from scr.classes.Session.Ui_NewSessionWindow import Ui_NewSession
from scr.classes.View.ThemeView import ThemeView


class CredentialsChooserWindow(QtWidgets.QMainWindow):
    def __init__(self, new_session_ui: Ui_NewSession):
        self.new_session_ui = new_session_ui
        super().__init__()

    def setupUi(self, Dialog):
        self.Dialog = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 300)
        Dialog.setAcceptDrops(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.remove_button = QtWidgets.QPushButton(Dialog)
        self.remove_button.setObjectName("remove_button")
        self.horizontalLayout.addWidget(self.remove_button)
        self.choose_button = QtWidgets.QPushButton(Dialog)
        self.choose_button.setObjectName("choose_button")
        self.horizontalLayout.addWidget(self.choose_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.init_components()

    def init_components(self):
        self.model = QtGui.QStandardItemModel()
        self.listView.setModel(self.model)
        self.update_shown_credentials()
        self.choose_button.clicked.connect(self.choose_button_clicked)
        self.listView.doubleClicked.connect(self.choose_button_clicked)
        self.remove_button.clicked.connect(self.remove_button_clicked)
        #self.choose_button.setDefault(True)

    def update_shown_credentials(self):
        self.model.clear()
        self.saved_credentials = CredentialHadler.get_saved_credentials()
        for credential in self.saved_credentials:
            item = QStandardItem(credential.host_name + " : " + credential.user_name)
            item.setEditable(False)
            item.setIcon(QIcon(QIcon('../icons/account-avatar-profile-human-man-user-30448.png')))
            self.model.appendRow(item)

    def choose_button_clicked(self):
        if(len(self.listView.selectionModel().selectedRows()) > 0):
            row = self.listView.selectionModel().selectedRows()[0].row()
            self.new_session_ui.set_credentials(self.saved_credentials[row])
            self.Dialog.close()

    def remove_button_clicked(self):
        if (len(self.listView.selectionModel().selectedRows()) > 0):
            row = self.listView.selectionModel().selectedRows()[0].row()
            CredentialHadler.remove_credential(self.saved_credentials[row])
            self.update_shown_credentials()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Saved Credentials"))
        self.remove_button.setText(_translate("Dialog", "Remove"))
        self.choose_button.setText(_translate("Dialog", "Choose"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = CredentialsChooserWindow()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
